version: '3.3'

services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile/php.Dockerfile
        volumes:
            - "./:/var/www"
    nginx:
        build:
            context: ./
            dockerfile: ./Dockerfile/nginx.Dockerfile
        volumes:
            - "./:/var/www"
        ports:
            - "8080:80"
        links:
            - db
        depends_on:
            - app
    db:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=homestead"
        ports:
            - "33061:3306"