###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: wolnybot-mysql
      working_dir: /application
      volumes:
        - ./application:/application
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=docker
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpass
      ports:
        - "9193:3306"

    webserver:
      image: nginx:alpine
      container_name: wolnybot-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9191:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: wolnybot-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

